server.port: 8765

spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0 # 1.0 trace every request with percentage


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# it can discover other services from eureka
pring.cloud.gateway.discovery.locator.enabled: true
pring.cloud.gateway.discovery.locator.lower-case-service-id: true
