spring:
  application:
    name: limits-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      profile: default
  sleuth:
    sampler:
      probability: 1.0 # 1.0 trace every request with percentage

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

limits-service:
  maximum: 100
  minimum: 1


