server.port: 8100

spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0 # 1.0 trace every request with percentage


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka